name: "Meticulous Run"
description: "Run automated Meticulous tests"
inputs:
  api_token:
    description: "Meticulous API token"
    required: true
    default: ""
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
