name: "Meticulous Run"
description: "Run automated Meticulous tests"
inputs:
  api-token:
    description: "Meticulous API token"
    required: true
    default: ""
  arguments:
    description: "CLI arguments"
    required: true
    default: ""
outputs: {}
runs:
  using: "docker"
  image: "docker://ghcr.io/alwaysmeticulous/report-diffs-action:main"
  env:
    API_TOKEN: ${{ inputs.api-token }}
