name: "Meticulous - Report Diffs"
description: "Run automated Meticulous tests"
inputs:
  api-token:
    description: "Meticulous API token"
    required: true
  github-token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    required: true
    default: ${{ github.token }}
  app-url:
    description: "The URL to execute the tests against. This URL should serve the code from the current commit (e.g. a localhost URL served up by a local server)"
    required: true
  tests-file:
    description: |
      The path to the meticulous.json file containing the list of tests you want to run.

      If not set a search will be performed to find a meticulous.json file in the current directory or the nearest parent directory.
    required: false
  arguments:
    description: "CLI arguments"
    required: true
    default: ""
outputs: {}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    API_TOKEN: ${{ inputs.api-token }}
    APP_URL: ${{ inputs.app-url }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
branding:
  color: purple
  icon: camera
