name: "Meticulous Run"
description: "Run automated Meticulous tests"
inputs:
  api-token:
    description: "Meticulous API token"
    required: true
    default: ""
  github-token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    default: ${{ github.token }}
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
