name: "Meticulous - Report Diffs"
description: "Run automated Meticulous tests"
inputs:
  api-token:
    description: "Meticulous API token"
    required: true
  github-token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    required: true
    default: ${{ github.token }}
  app-url:
    description: "The URL to execute the tests against. This URL should serve the code from the current commit (e.g. a localhost URL served up by a local server)"
    required: true
  tests-file:
    description: |
      The path to the meticulous.json file containing the list of tests you want to run.

      If not set a search will be performed to find a meticulous.json file in the current directory or the nearest parent directory.
    required: false
  max-retries-on-failure:
    description: |
      The number of times to re-run any replays that give a screenshot diff. If any of the retryed replays differs from that in the first replay
      then the original diff will be marked as a flake, and ignored.

      Setting to 0 disables this feature.
    required: true
    default: 5
outputs: {}
runs:
  using: "docker"
  image: "docker://ghcr.io/alwaysmeticulous/report-diffs-action:releases-v1"
  env:
    API_TOKEN: ${{ inputs.api-token }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    APP_URL: ${{ inputs.app-url }}
    TESTS_FILE: ${{ inputs.tests-file }}
    MAX_RETRIES_ON_FAILURE: ${{ inputs.max-retries-on-failure }}
branding:
  color: purple
  icon: camera
