blockExoticSubdeps: true
minimumReleaseAge: 10800 # 7 days
trustPolicy: no-downgrade
minimumReleaseAgeExclude:
  - "@alwaysmeticulous/*"
trustPolicyExclude:
  - "eslint-import-resolver-typescript@3.10.1"
  - "undici-types@6.21.0"
  - "semver@6.3.1"
  - "undici@5.29.0"