name: "Meticulous - Report Diffs (Cloud Compute)"
description: "Run automated Meticulous tests in Meticulous' cloud."
inputs:
  api-token:
    description: "Meticulous API token"
    required: true
  github-token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    required: true
    default: ${{ github.token }}
  app-url:
    description: |
      The URL to execute the tests against. This URL should serve the code from the current commit (e.g. a localhost URL served up by a local server).
    required: true
  head-sha:
    description: |
      Override the head commit SHA that we are analysing instead of using the one inferred automatically by Meticulous. This normally should not be set, but is useful in some scenarios.
    required: false

outputs: {}
runs:
  using: node20
  main: "../out/cloud-compute.entrypoint.js"
  post: "../out/post.entrypoint.js"
branding:
  color: purple
  icon: camera
