# Workflow for building and publishing this action's container image

name: Build and Publish

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: {}
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  lint-test-check-transpile:
    name: Lint, format and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Format
        run: yarn format:check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build actions
        id: build
        run: yarn build
        env:
          SENTRY_ORG: meticulous
          SENTRY_PROJECT: sdk
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Check JS Transpile
        id: diff
        run: |
          FILTERED_DIFF=$(git diff --unified=0 --ignore-space-at-eol --text out/ | grep -v -E '(+++|---|index [0-9a-f]{7}\.\.[0-9a-f]{7})' | grep -v -E '(require\$\$[0-9]+\$[a-zA-Z0-9]+|[a-zA-Z_][a-zA-Z0-9_]*\$[a-zA-Z0-9]+)')
          if [ "$(echo "$FILTERED_DIFF" | wc -l)" -gt "1" ] && [ -n "$(echo "$FILTERED_DIFF" | tr -d '[:space:]')" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            echo "$FILTERED_DIFF"
            echo ""
            echo "Run 'yarn build' locally and commit the changes."
            echo ""
            exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref }}
    needs: lint-test-check-transpile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/alwaysmeticulous/report-diffs-action
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Configure GHCR credentials
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/alwaysmeticulous/report-diffs-action:cache
          cache-to: type=registry,ref=ghcr.io/alwaysmeticulous/report-diffs-action:cache,mode=max

      - name: Bump V1 tag
        if: github.ref == 'refs/heads/releases/v1'
        run: |
          git fetch origin releases/v1 --tags
          git tag --delete v1
          git tag v1 origin/releases/v1
          git push --tag --force
