# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read
  statuses: write

jobs:
  test-custom-summary:
      runs-on: ubuntu-latest
      name: Testing making a custom summary

      steps:
        - name: Custom summary
          run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

  test:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Meticulous"
          description: "Testing against 37 user sessions..."
          state: "pending"
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: https://meticulous.ai

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json
          
      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Meticulous"
          description: "Differences found for 3 of 37 sessions, click details to view"
          state: "success"
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: https://meticulous.ai

      - name: Run Meticulous tests
        id: test
        uses: ./
        continue-on-error: true
        with:
          api_token: "${{ secrets.METICULOUS_API_TOKEN }}"
          arguments: |
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests.json"
            --parallelize
            --parallelTasks=8
            --useAssetsSnapshottedInBaseSimulation
            --storyboard
            --headless
            --noSandbox
