# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - uses: actions/checkout@v3
      - name: Run CLI command show-project
        id: show-project
        uses: ./
        with:
          api_token: "${{ secrets.METICULOUS_API_TOKEN }}"
