# Workflow for automated Meticulous tests

name: Tests - react-bmi-calculator

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: {}

permissions:
  contents: read
  statuses: write
  pull-requests: write
  packages: read
  deployments: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use local dockerfile
        run: node ./scripts/use-local-dockerfile.js

      - name: Run report-diffs-action
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          use-deployment-url: "true"
          tests-file: tests/react-bmi-calculator/meticulous.json
          test-suite-id: "test Meticulous with deployment url"
