# Workflow for automated Meticulous tests

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - name: Hello world action step
        id: hello
        uses: alwaysmeticulous/action-meticulous-run@9e9cf1353af4503b45062a054ccf8442e652d46c
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
