# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Differences found for 3 of 37 sessions"
          description: "Passed (differences found for 3 of 37 sessions)"
          state: "success"
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: https://meticulous.ai

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - name: Run Meticulous tests
        id: test
        uses: ./
        with:
          api_token: "${{ secrets.METICULOUS_API_TOKEN }}"
          arguments: |
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests.json"
            --parallelize
            --parallelTasks=8
            --useAssetsSnapshottedInBaseSimulation
            --storyboard
            --headless
            --noSandbox
