# Workflow for automated Meticulous tests

name: Tests - react-bmi-calculator

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run report-diffs-action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        id: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: tests/react-bmi-calculator/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        id: dependencies
        working-directory: ./tests/react-bmi-calculator
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build project
        id: build
        working-directory: ./tests/react-bmi-calculator
        run: yarn build

      - name: Serve project
        id: serve
        working-directory: ./tests/react-bmi-calculator
        run: |
          yarn serve &
          sleep 5

      - name: Run report-diffs-action
        id: test
        uses: ./
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          arguments: |
            --appUrl="http://172.17.0.1:3000/"
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests/react-bmi-calculator/meticulous.json"
            --parallelize
            --parallelTasks=8
            --storyboard
            --headless
            --noSandbox
