# Workflow for automated Meticulous tests

name: Tests - react-bmi-calculator

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: {}

permissions:
  contents: read
  statuses: write
  pull-requests: write
  packages: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        id: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            tests/react-bmi-calculator/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Use local dockerfile
        run: node ./scripts/use-local-dockerfile.js

      - name: Check base commit
        id: check-base-commit
        uses: ./
        with:
          command: check-base-commit
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          app-url: http://localhost:3000
          tests-file: tests/react-bmi-calculator/meticulous.json

      - name: Print output of previous step
        run: |
          echo "Got ${{ steps.check-base-commit.outputs.base-test-run }}"

      - name: Checkout base commit
        # if: steps.check-base-commit.outputs.base-test-run == ''
        run: |
          git fetch
          git checkout ${{ steps.check-base-commit.outputs.base-commit }}

      - name: Install react-bmi-calculator dependencies
        working-directory: ./tests/react-bmi-calculator
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build react-bmi-calculator
        working-directory: ./tests/react-bmi-calculator
        run: yarn build

      - name: Serve react-bmi-calculator
        id: serve-base
        working-directory: ./tests/react-bmi-calculator
        run: |
          yarn serve &
          pid=$!
          echo "pid=${pid}" >> $GITHUB_OUTPUT
          sleep 4

      # - name: Run report-diffs-action
      #   id: test
      #   uses: ./
      #   with:
      #     api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
      #     app-url: http://localhost:3000
      #     tests-file: tests/react-bmi-calculator/meticulous.json

      - name: Shut down server
        run: |
          kill "${{ steps.serve-base.outputs.pid }}"

      - name: Checkout head commit
        # if: steps.check-base-commit.outputs.base-test-run == ''
        run: |
          git checkout ${{ steps.check-base-commit.outputs.head-commit }}

      - name: Install react-bmi-calculator dependencies
        working-directory: ./tests/react-bmi-calculator
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build react-bmi-calculator
        working-directory: ./tests/react-bmi-calculator
        run: yarn build

      - name: Serve react-bmi-calculator
        working-directory: ./tests/react-bmi-calculator
        run: |
          yarn serve &
          sleep 4

      - name: Run report-diffs-action
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          app-url: http://localhost:3000
          tests-file: tests/react-bmi-calculator/meticulous.json
