# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - name: Run Meticulous tests
        id: test
        uses: alwaysmeticulous/action-meticulous-run@run-tests
        with:
          api_token: "${{ secrets.METICULOUS_API_TOKEN }}"
          arguments: |
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests.json"
            --parallelize
            --parallelTasks=8
            --useAssetsSnapshottedInBaseSimulation
            --storyboard
            --headless
