# Workflow for automated Meticulous tests

name: Tests - react-bmi-calculator

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: {}

permissions:
  contents: read
  statuses: write
  pull-requests: write
  packages: read

jobs:
  test:
    name: Report diffs (using deployment url)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        id: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            tests/react-bmi-calculator/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install local dockerfile script dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Use local dockerfile
        run: node ./scripts/use-local-dockerfile.js

      - name: Run report-diffs-action
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          use-deployment-url: true
          allowed-environments: |
            Preview
          tests-file: tests/react-bmi-calculator/meticulous.json
          test-suite-id: "test Meticulous with deployment url"
