# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - name: Run Meticulous tests
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          app-url: https://localhost:3000
          tests-file: tests.json
