# Workflow for automated Meticulous tests

# This test tests that we can run Meticulous for two projects against the same commit, without
# anything clashing. Most of the tests use the 'public-tests' project, but this one uses 'public-tests-clone'.

name: Tests - react-bmi-calculator - public-tests-clone project

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: {}

permissions:
  contents: read
  statuses: write
  pull-requests: write
  packages: read

jobs:
  test:
    name: Report diffs (public-tests-clone project)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        id: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            tests/react-bmi-calculator/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install local dockerfile script dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Use local dockerfile
        run: node ./scripts/use-local-dockerfile.js

      - name: Run report-diffs-action (using public-tests-clone project)
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN_FOR_PUBLIC_TESTS_CLONE_PROJECT }}"
          use-deployment-url: true
          tests-file: tests/react-bmi-calculator/meticulous.public-tests-clone-project.json
          test-suite-id: "test Meticulous with deployment url (public-tests-clone project)"
