# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: LouisBrunner/checks-action@v1.1.1
        id: initial_check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Testing change against 37 user sessions...
          status: in_progress
          output: |
            {"summary":"Test"}
          action_url: https://meticulous.ai/action
          details_url: https://meticulous.ai/details

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Differences found for 3 of 37 user sessions
          conclusion: ${{ job.status }}
          output: |
            {"summary":"Differences found for [3 of 37 user sessions](https://meticulous.ai)"}
          action_url: https://meticulous.ai/action
          details_url: https://meticulous.ai/details
          check_id: ${{ steps.initial_check.outputs.check_id }}

      - name: Run Meticulous tests
        id: test
        uses: ./
        with:
          api_token: "${{ secrets.METICULOUS_API_TOKEN }}"
          arguments: |
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests.json"
            --parallelize
            --parallelTasks=8
            --useAssetsSnapshottedInBaseSimulation
            --storyboard
            --headless
            --noSandbox
