# Workflow for automated Meticulous tests

name: Meticulous

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read
  statuses: write
  pull-requests: write
  packages: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        id: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        id: dependencies
        run: |
          yarn install --frozen-lockfile --non-interactive

      - name: Build project
        id: build
        run: |
          yarn build

      - name: Use local dockerfile
        run: node ./scripts/use-local-dockerfile.js

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - name: Run report-diffs-action
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          app-url: https://localhost:3000
          tests-file: tests.json
