# Workflow for automated Meticulous tests

name: Meticulous

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - name: Run Meticulous tests
        id: test
        uses: ./
        with:
          api-token: "${{ secrets.METICULOUS_API_TOKEN }}"
          arguments: |
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests.json"
            --parallelize
            --parallelTasks=8
            --useAssetsSnapshottedInBaseSimulation
            --storyboard
            --headless
            --noSandbox
