# Workflow for automated Meticulous tests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the Meticulous action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"Test"}

      - name: Write tests.json
        id: tests_json
        run: |
          echo '${{ secrets.TEST_SUITE_JSON }}' > tests.json

      - name: Run Meticulous tests
        id: test
        uses: ./
        with:
          api_token: "${{ secrets.METICULOUS_API_TOKEN }}"
          arguments: |
            --diffThreshold="0"
            --skipPauses
            --testsFile="tests.json"
            --parallelize
            --parallelTasks=8
            --useAssetsSnapshottedInBaseSimulation
            --storyboard
            --headless
            --noSandbox
