# Integration Tests Workflow

name: Integration Tests

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run unit tests
        run: yarn test:unit

      - name: Run integration tests
        run: yarn test:integration

      - name: Run linting
        run: yarn lint

      - name: Check formatting
        run: yarn format:check